print('*****\t***** *\t   * ******  *****\t  ***\t**\t *****', end='\n')
print('*\t * *\t* *\t   * *\t\t*\t\t *\t*  *  *\t *\t  *',end='\n')
print('*\t * *\t* *\t   * *\t\t*\t\t*\t* *\t   * *\t  *', end='\n')
print('*****\t***** *\t   * *\t\t*\t   *\t* *\t   * *****',end='\n')
print('*\t *\t  *\t*  ***** ****\t*\t   *\t* *\t   * *\t  *',end='\n')
print('*\t *\t *\t*\t   * *\t\t*\t   *\t* ****** *\t  *',end='\n')
print('*\t *\t*\t*\t   * *\t\t*\t   *\t* *\t   * *\t  *',end='\n')
print('*\t * *\t*\t   * *\t\t*\t   *\t* *\t   * *\t  *',end='\n')
print('***** * \t*\t   * ******\t ***** *\t* *\t   * *****')